### ISSUE TITLE
Feature Request: Add Default Thumbnail Generate Support

### ISSUE THREAD

**Issue by Abishekjen** [Mrvishal2k2/TG-RenameBot#8]
Convert/Rename as Video by default Generate Thumbnail,But Convert/Rename as File no Thumbnail Shows by default if no Thumbnail Saved.

**Comment by Abishekjen** [comment]
Convert/Rename as Video by default Generate Thumbnail,But Convert/Rename as File no Thumbnail Shows by default if no Thumbnail Saved.

**Comment by Mrvishal2k2** [comment]
> Convert/Rename as Video by default Generate Thumbnail,But Convert/Rename as File no Thumbnail Shows by default if no Thumbnail Saved.

Yes that's how I coded it to happen
It looks cringe to see random screenshots while in file format when no thumb is saved

In video if random thumb is not used in no thumb saved situation it looks black thumb
Which is really ugly
So i added it to overcome it

In file case
If u use random thumb on file in no thumb saved situation, it makes it really creepy
